// Class: ReadBDTDD2012Fisher
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTDD2012Fisher
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/01       [393729]
Creator        : voss
Date           : Sat Nov 22 10:57:08 2014
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-431.29.2.el6.x86_64 #1 SMP Wed Sep 10 11:13:12 CEST 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/voss/Datenanalyse/DD-Training
Training events: 12001
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
UseFisherCuts: "True" [Use multivariate splits using the Fisher criterion]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 20
log_pi_IP                     log_pi_IP                     log_pi_IP                     log_pi_IP                                                       'F'    [-1.51923286915,1.04128730297]
log_p_IP                      log_p_IP                      log_p_IP                      log_p_IP                                                        'F'    [-1.55906772614,0.696034431458]
log_Lpi_IP                    log_Lpi_IP                    log_Lpi_IP                    log_Lpi_IP                                                      'F'    [0.0131395924836,2.0077559948]
log_Lp_IP                     log_Lp_IP                     log_Lp_IP                     log_Lp_IP                                                       'F'    [-0.481942236423,1.35506546497]
log_BIP                       log_BIP                       log_BIP                       log_BIP                                                         'F'    [-4.45256614685,-0.77402150631]
log_LIP                       log_LIP                       log_LIP                       log_LIP                                                         'F'    [-2.44553732872,0.706591188908]
log_BVtxchi2                  log_BVtxchi2                  log_BVtxchi2                  log_BVtxchi2                                                    'F'    [0.0551982149482,4.9922785759]
FitProb                       FitProb                       FitProb                       FitProb                                                         'F'    [1.14490721899e-05,0.999765396118]
log_B_DauSumchi2              log_B_DauSumchi2              log_B_DauSumchi2              log_B_DauSumchi2                                                'F'    [1.29851078987,5.05440044403]
log_B_FLBchi2                 log_B_FLBchi2                 log_B_FLBchi2                 log_B_FLBchi2                                                   'F'    [0.790921747684,2.81794953346]
log_Lambda_FDchi2             log_Lambda_FDchi2             log_Lambda_FDchi2             log_Lambda_FDchi2                                               'F'    [0.752305984497,3.22746706009]
B_PT                          B_PT                          B_PT                          B_PT                                                            'F'    [1492.55407715,48625.7695312]
B_Eta                         B_Eta                         B_Eta                         B_Eta                                                           'F'    [2.31465554237,5.55322599411]
log_B_ctau                    log_B_ctau                    log_B_ctau                    log_B_ctau                                                      'F'    [-1.23079657555,0.496834427118]
log_L_ctau                    log_L_ctau                    log_L_ctau                    log_L_ctau                                                      'F'    [0.811039686203,2.48783326149]
BWerner                       BWerner                       BWerner                       BWerner                                                         'F'    [4.11361133956e-06,0.0299989879131]
LWerner                       LWerner                       LWerner                       LWerner                                                         'F'    [-3.85285067558,-0.35182890296]
ppiDist                       ppiDist                       ppiDist                       ppiDist                                                         'F'    [3.96544828618e-06,0.129972323775]
LAngle                        LAngle                        LAngle                        LAngle                                                          'F'    [0.0188157968223,3.13562917709]
Pointing                      Pointing                      Pointing                      Pointing                                                        'F'    [4.84630254505e-05,0.474036633968]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN_DD new BDTDD2012FisherNode
   
#ifndef BDTDD2012FisherNode__def
#define BDTDD2012FisherNode__def
   
class BDTDD2012FisherNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTDD2012FisherNode ( BDTDD2012FisherNode* left,BDTDD2012FisherNode* right,
                          int nFisherCoeff,
                          double fisherCoeff0,
                          double fisherCoeff1,
                          double fisherCoeff2,
                          double fisherCoeff3,
                          double fisherCoeff4,
                          double fisherCoeff5,
                          double fisherCoeff6,
                          double fisherCoeff7,
                          double fisherCoeff8,
                          double fisherCoeff9,
                          double fisherCoeff10,
                          double fisherCoeff11,
                          double fisherCoeff12,
                          double fisherCoeff13,
                          double fisherCoeff14,
                          double fisherCoeff15,
                          double fisherCoeff16,
                          double fisherCoeff17,
                          double fisherCoeff18,
                          double fisherCoeff19,
                          double fisherCoeff20,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fNFisherCoeff ( nFisherCoeff ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
     fFisherCoeff.push_back(fisherCoeff0);
     fFisherCoeff.push_back(fisherCoeff1);
     fFisherCoeff.push_back(fisherCoeff2);
     fFisherCoeff.push_back(fisherCoeff3);
     fFisherCoeff.push_back(fisherCoeff4);
     fFisherCoeff.push_back(fisherCoeff5);
     fFisherCoeff.push_back(fisherCoeff6);
     fFisherCoeff.push_back(fisherCoeff7);
     fFisherCoeff.push_back(fisherCoeff8);
     fFisherCoeff.push_back(fisherCoeff9);
     fFisherCoeff.push_back(fisherCoeff10);
     fFisherCoeff.push_back(fisherCoeff11);
     fFisherCoeff.push_back(fisherCoeff12);
     fFisherCoeff.push_back(fisherCoeff13);
     fFisherCoeff.push_back(fisherCoeff14);
     fFisherCoeff.push_back(fisherCoeff15);
     fFisherCoeff.push_back(fisherCoeff16);
     fFisherCoeff.push_back(fisherCoeff17);
     fFisherCoeff.push_back(fisherCoeff18);
     fFisherCoeff.push_back(fisherCoeff19);
     fFisherCoeff.push_back(fisherCoeff20);
   }

   virtual ~BDTDD2012FisherNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTDD2012FisherNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTDD2012FisherNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTDD2012FisherNode*   fLeft;     // pointer to the left daughter node
   BDTDD2012FisherNode*   fRight;    // pointer to the right daughter node
   int                     fNFisherCoeff; // =0 if this node doesn use fisher, else =nvar+1 
   std::vector<double>     fFisherCoeff;  // the fisher coeff (offset at the last element)
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTDD2012FisherNode::~BDTDD2012FisherNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTDD2012FisherNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
   if (fNFisherCoeff == 0){
     result = (inputValues[fSelector] > fCutValue );
   }else{
     double fisher = fFisherCoeff.at(fFisherCoeff.size()-1);
     for (unsigned int ivar=0; ivar<fFisherCoeff.size()-1; ivar++)
       fisher += fFisherCoeff.at(ivar)*inputValues.at(ivar);
     result = fisher > fCutValue;
   }
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTDD2012FisherNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTDD2012Fisher : public IClassifierReader {

 public:

   // constructor
   ReadBDTDD2012Fisher( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTDD2012Fisher" ),
        fNvars( 20 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "log_pi_IP", "log_p_IP", "log_Lpi_IP", "log_Lp_IP", "log_BIP", "log_LIP", "log_BVtxchi2", "FitProb", "log_B_DauSumchi2", "log_B_FLBchi2", "log_Lambda_FDchi2", "B_PT", "B_Eta", "log_B_ctau", "log_L_ctau", "BWerner", "LWerner", "ppiDist", "LAngle", "Pointing" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTDD2012Fisher() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[20];
   double fVmax[20];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[20];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTDD2012FisherNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTDD2012Fisher::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTDD2012FisherNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTDD2012FisherNode*)current->GetRight();
         else current=(BDTDD2012FisherNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDTDD2012Fisher::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.925672878899949);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 5999.58, 0, 1, 0.944208,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.792228,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.447768,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5206.11, 0, 0, 0.643566,-99) , 
21, 0, 0, 0, -0.0752115, 0, -0.0452594, 0.0488705, 0.312626, -0.482563, 1.42158, 0, 0, 0, -0.282763, -0.0989976, 46.8712, 0, 0, 0, -11.341, -0.643219, 20, -0.0587638, 0, 0, 0.865161,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.610156,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.240684,-99) , 
21, 0, 0, 0, -0.0494698, 0, 0.566644, 0.0383179, 0.398449, -1.17624, 2.41451, 0, 0, 0, -0.61116, -0.0511447, -2.83289, 0, 0, -0.505604, -3.42791, 1.15112, 20, 0.0220683, 0, 0, 0.420856,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0.122507, 1, -1, 0.108947,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5802.68, 0, 0, 0.167464,-99) , 
21, 0, 0, 0, -0.0245179, 0, -0.151031, 0.0787866, 0.561486, -0.958749, 2.49095, 0, 0, 0, -0.136124, -0.161159, 3.77462, 0, 0, 0, -5.72143, -0.549253, 20, 0.109296, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.597001);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.0504917, 0, -0.0176571, 0.0469186, 0.333362, -0.355296, 1.1763, 0, 0, 0, -0.229528, -0.0339943, 35.5295, 0, 0, 0, -7.44099, -0.858769, -1, 0.0118192, 0, 1, 0.813791,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.551398,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.329779,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 1.69522, 0, 0, 0.439868,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.11901, 0, -1, 0.170608,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.115087, 1, 0, 0.291125,-99) , 
21, 0, 0, 0, 0.00943805, 0, -0.13227, 0.0642292, 0.428098, -0.633271, 1.63339, 0, 0, 0, 0.0417276, -0.0398096, 1.76176, 0, 0, 0, -3.3867, -0.489023, 20, 0.111912, 0, 0, 0.518674,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.411098);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.0210838, 0, -0.0386371, 0.0428445, 0.328382, -0.398573, 1.27033, 0, 0, 0, -0.250012, -0.131583, 38.7782, 0, 0, 0, -8.21027, -0.780099, -1, 0.0247676, 0, 1, 0.76122,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.532152,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.282773,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.52571, 0, 0, 0.464333,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.25882, 0, -1, 0.217329,-99) , 
21, 0, 0, 0, -0.0736131, 0, -0.137327, 0.0434857, 0.212703, -0.898852, 1.72454, 0, 0, 0, 0.284572, -0.0628927, 8.76068, 0, 0, 0, -2.29579, 0.347253, 20, -0.0330053, 0, 0, 0.367935,-99) , 
21, 0, 0, 0, -0.0531797, 0, -0.0696021, 0.0504665, 0.317274, -0.601678, 1.42423, 0, 0, 0, 0.0395128, -0.0991264, 7.91638, 0, 0, 0, -2.58411, -0.181454, 20, 0.114705, 0, 0, 0.501202,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.344665);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.24236, 1, 1, 0.828137,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.490281,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5999.58, 0, 0, 0.742696,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.535518,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.3353,-99) , 
21, 0, 0, 0, -0.0694014, 0, 0.0257273, 0.00456406, 0.159337, -0.0377903, 0.198677, 0, 0, 0, -0.291538, 0.00218507, 2.5777, 0, 0, 0, -1.38946, -0.170221, 20, -0.033044, 0, 0, 0.467924,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 7239.39, 0, -1, 0.281075,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.728207, 0, 0, 0.38663,-99) , 
21, 0, 0, 0, -0.0166353, 0, -0.0317076, 0.0295741, 0.258925, -0.464462, 1.14122, 0, 0, 0, -0.0432014, -0.105805, 5.33312, 0, 0, 0, -1.73849, -0.195378, 20, 0.128431, 0, 0, 0.472179,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.319774);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
21, 0, 0, 0, 0.146428, 0, 0, 0.0695179, 0.410896, -0.21809, 0.496925, 0, 0, 0, 0.112901, -0.284566, 51.4555, 0, 0, 0, -12.0906, 0.0166179, -1, 0.037471, 0, 1, 0.839437,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.678963,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.440714,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 1.56035, 0, 0, 0.565058,-99) , 
21, 0, 0, 0, 0.0702618, 0, 0, 0.104246, 0.504819, -0.286655, 1.05842, 0, 0, 0, -0.237477, -0.156104, 37.5462, 0, 0, 0, -7.73332, -1.00606, 20, -0.0187701, 0, 0, 0.72867,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.55527,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.234243,-99) , 
21, 0, 0, 0, -0.076502, 0, -0.0560598, -0.0394394, 0.260837, 0.319035, -0.507416, 0, 0, 0, -0.467851, 0.104692, 1.88281, 0, 0, 0, -1.42333, -0.387662, 20, -0.143861, 0, 0, 0.504476,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, 0.0498622, 0, -0.00405478, 0.0784764, 0.245123, -0.117642, 0.154896, 0, 0, 0, 0.250741, -0.162076, -1.64455, 0, 0, 0, -0.74352, 0.374163, -1, -0.0290516, 0, -1, 0.344369,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.17537, 0, 0, 0.409152,-99) , 
21, 0, 0, 0, 0.01734, 0, -0.0253379, 0.042477, 0.283212, -0.434964, 1.00796, 0, 0, 0, 0.000637733, -0.116266, 5.04693, 0, 0, 0, -1.2727, -0.134488, 20, 0.112504, 0, 0, 0.477058,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.292519);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.997793,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 8234.19, 0, 1, 0.623979,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -0.942678, 0, -1, 0.373297,-99) , 
21, 0, 0, 0, 0.00186502, 0, -0.0259422, 0.0396493, 0.271593, -0.316318, 0.698385, 0, 0, 0, 0.0587548, -0.363643, 3.35976, 0, 0, 0, -1.10501, 0.419721, 20, 0.0428536, 0, 0, 0.462187,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.485924,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.320182);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.997045,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.757736,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.252257,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.39798, 1, 0, 0.641051,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.563538,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.379106,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.398649, 0, 0, 0.432377,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 8225.87, 0, 0, 0.482671,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.503012,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.211799);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.995934,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.636432,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.452938,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.70261, 0, 0, 0.514872,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.14355,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.69037, 1, 0, 0.497712,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.515163,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.26377);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.99498,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.637346,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.438902,-99) , 
21, 0, 0, 0, 0.0293188, 0, -0.0354161, 0.0389793, 0.114386, -0.793887, 1.09749, 0, 0, 0, 0.4258, -0.136585, 1.57236, 0, 0, 0, -0.761895, 0.9819, 20, -0.0248177, 0, 0, 0.555537,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, 0, 0, 0.0703747, 0.0779544, 0.542209, 0.3302, -0.417178, 0, 0, 0, -0.528043, 0, 39.4408, 0, 0, 0, -3.71555, -0.638667, -1, -0.15421, 0, -1, 0.331074,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.24511, 1, 0, 0.51682,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.532153,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.183909);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.993475,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.556563,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.216719,-99) , 
21, 0, 0, 0, 0.0466765, 0, 0.0209512, 0.0141671, 0.117054, -0.147474, 0.380296, 0, 0, 0, -0.172123, -0.0880763, 4.30979, 0, 0, 0, -0.451076, -0.126446, 20, -0.0775156, 0, 0, 0.540425,-99) , 
NN_DD(
0, 
0, 
21, 0.961282, 0, 0, -0.0017364, 0, 0.590161, 0.0829257, 0.213888, -0.540015, 0.355462, 0, 0, 0, -1.65038, -0.0897214, 20.1146, 0, 0, 0, -3.45236, 0.828423, -1, 0.0268359, 0, -1, 0.302079,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1.02214, 0, 0, 0.519195,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.532893,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.156387);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.992167,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.638194,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.467865,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 8225.87, 0, 0, 0.502033,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.76812, 1, -1, 0.269203,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.54195, 1, 0, 0.485268,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 2.00875, 0, 0, 0.498808,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.169837);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.59279,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.477114,-99) , 
21, 0, 0, 0, 0.0948548, 0, -0.193583, 0.0403483, 0.0929083, -0.302243, 0.374808, 0, 0, 0, 0.350756, -0.0245717, 2.39095, 0, 0, 0, -0.412111, 0.258849, 20, -0.0208385, 0, 0, 0.552033,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.271933,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.69037, 1, 0, 0.541603,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.510036,-99) , 
NN_DD(
0, 
0, 
21, 0.552268, 0, 0, 0, 0, 0, -0.0841884, -0.485107, 0.160527, -0.617802, 0, 0, 0, -0.436588, 0, 2.10226, 0, 0, 0, -1.54518, 0.827256, -1, -0.00987608, 0, -1, 0.24116,-99) , 
21, 0, 0.0903893, 0, 0, 0, 0, 0.0388069, 0.326988, -0.273742, 0.751894, 0, 0, 0, -0.284426, 0, 0.46088, 0, 0, 0, -1.08438, -0.474745, 20, 0.0630966, 0, 0, 0.318881,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.51884, 1, 0, 0.521867,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.16966);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.560757,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.322142,-99) , 
21, 0, 0, 0, 0.0439769, 0, -0.0474445, 0.0165668, 0.0892315, 0.0495124, -0.0344115, 0, 0, 0, -0.0573229, -0.0258513, 0.714935, 0, 0, 0, -0.175462, -0.162791, 20, -0.0466471, 0, 0, 0.54197,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.279488,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -3.05122, 0, 0, 0.531532,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 7502.75, 0, -1, 0.331411,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.51884, 1, 0, 0.514113,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.145719);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.596475,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.480914,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0185709, 1, 0, 0.525798,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.544036,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.342313,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.90131, 0, 0, 0.396255,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.08574, 0, 0, 0.500191,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.0197471, 0, 0, 0.0350332, 0.4397, 0.21794, -0.324313, 0, 0, 0, 0, 0.207778, 8.25402, 0, 0, 0, -0.220194, -0.646068, -1, -0.0309188, 0, -1, 0.32447,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.54195, 1, 0, 0.487907,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.173123);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.618719,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.494788,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.43993, 0, 0, 0.549993,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.582224,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.376846,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.91083, 0, 0, 0.418792,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.09669, 1, 0, 0.518707,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.61851,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.378809,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.74477, 0, 0, 0.481587,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -0.699333, 0, -1, 0.22116,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 4278.43, 0, 0, 0.393888,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.909585, 0, 0, 0.499612,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.149908);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.552878,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.36406,-99) , 
21, 0, 0, 0, 0.0383797, 0, 0.0427962, -0.0120667, 0.0191994, 0.0250184, 0.0159411, 0, 0, 0, -0.143601, 0.0252895, 4.30646, 0, 0, 0, -0.228777, -0.194249, 20, -0.0483419, 0, 0, 0.538964,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.546504,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.233508,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.67368, 0, 0, 0.354576,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.524669,-99) , 
NN_DD(
0, 
0, 
21, 1.00806, 0, 0.343102, -0.203928, 0, 0.662614, 0.100999, 0.186146, -0.420686, 0.175099, 0, 0, 0, -1.772, -0.0819437, 19.1329, 0, 0, 0, -3.34207, 0.404061, -1, -0.0308001, 0, -1, 0.36219,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1.02214, 0, 0, 0.510817,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.122171);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.744699,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.52209,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.372289,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.06334, 0, 0, 0.498543,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1.0132, 0, 0, 0.507542,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.584962,-99) , 
NN_DD(
0, 
0, 
21, 0, 0.0373699, 0, 0, 0, 0, -0.00938585, 0.152917, -0.277282, 0.576532, 0, 0, 0, 0.00803883, 0, 15.56, 0, 0, 0, -0.804176, -0.104924, -1, -0.00594429, 0, -1, 0.370686,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.26606, 1, 0, 0.40252,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.68555, 1, 0, 0.487555,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.158293);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.543539,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.398089,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.909585, 0, 0, 0.52377,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.66158, 0, -1, 0.356677,-99) , 
21, 0, 0, 0, -0.0251082, 0, 0.0462019, 0.0253476, 0.00561537, -0.45608, 0.618704, 0, 0, 0, 0.219377, 0.0157354, 5.71299, 0, 0, 0, -0.61999, 0.4797, 20, -0.0600811, 0, 0, 0.497938,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.519163,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.311727,-99) , 
21, 0, 0, 0, 0.0752804, 0, -0.502587, 0.0397464, 0.199815, 0.0248465, -0.334233, 0, 0, 0, 0.599555, 0.142421, -3.31681, 0, 0, 0, -1.1953, 0.142922, 20, -0.0208352, 0, 0, 0.428243,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.179738,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.7894, 1, 0, 0.401234,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.09669, 1, 0, 0.474226,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.13557);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1.49297, 1, 1, 0.63069,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.542622,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.373507,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.67676, 1, 0, 0.442749,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.393084, 0, 0, 0.540986,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.00986775, 0, -0.0546199, 0.00779126, -0.00730338, 0.0231019, -0.22844, 0, 0, 0, 0.0924824, 0.060422, 5.35001, 0, 0, 0, -0.377355, 0.135413, -1, -0.0552304, 0, -1, 0.442383,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.0226193, 1, 0, 0.459976,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.101688);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.612614,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.491059,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.85683, 0, 0, 0.51084,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.237048,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -3.08207, 0, 0, 0.501658,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.584115,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.419691,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1.38285, 0, 0, 0.4993,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.62701, 1, -1, 0.323175,-99) , 
21, 0, 0, 0, 0, 0, -0.0843686, 0.0335922, 0.304037, 0.275498, -0.46151, 0, 0, 0, -0.164952, 0, 31.9654, 0, 0, 0, -2.60353, -0.258235, 20, 0.00501064, 0, 0, 0.403037,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.24511, 1, 0, 0.485008,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.103189);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1.95486, 0, 1, 0.533827,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.245758,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -3.08207, 0, 0, 0.524257,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.516385,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.392326,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 1.37009, 1, 0, 0.465719,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.05378, 1, -1, 0.309885,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.59155, 1, 0, 0.431291,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.09669, 1, 0, 0.501894,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.109536);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.678825,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.517094,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.402913,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.1061, 1, 0, 0.490184,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.534443,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.273874,-99) , 
21, 0, 0, 0, -0.289696, 0, -0.160716, 0.110099, 0.0357263, -0.352598, 0.267662, 0, 0, 0, 0.901913, 0.379472, 0.202634, 0, 0, 0, -0.429918, 0.374117, 20, -0.0178183, 0, 0, 0.395499,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.70088, 0, 0, 0.47694,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1.00516, 0, 0, 0.484021,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.112082);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.654492,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.577931,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.470439,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.134911, 0, 0, 0.488123,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -0.0308602, 1, -1, 0.419538,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 3736.99, 0, 0, 0.464561,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1.00516, 0, 0, 0.471132,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0791132);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.605446,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.499676,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.097304, 0, 0, 0.512273,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.32022,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.159124, 1, 0, 0.505205,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.63568,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.444079,-99) , 
21, 0, 0, 0, -0.0251615, 0, -0.0321511, 0.15513, 0.510875, 0.0532881, -0.419825, 0, 0, 0, 0.107019, 0.0628501, 4.36305, 0, 0, 0.183311, -0.350305, -0.406504, 20, -0.0299002, 0, 0, 0.558533,-99) , 
NN_DD(
0, 
0, 
21, 0.507305, 0, 0.0422847, -0.260719, 0, 0.225869, -0.0635746, -0.347941, -0.546175, 0.707688, 0, 0, 0, -0.784604, 0.0687737, 14.6831, 0, 0, 0, -1.99723, 0.710447, -1, -0.00317312, 0, -1, 0.336315,-99) , 
21, 0.560065, 0, 0, -0.104286, 0, 0.328502, 0.000857447, -0.0899799, -0.331001, 0.172306, 0, 0, 0, -0.927702, 0.0514782, 12.569, 0, 0, 0, -1.80041, 0.5915, 20, 0.0271893, 0, 0, 0.422858,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.914753, 0, 0, 0.491295,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.119182);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.543714,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.464365,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 1.33878, 0, 0, 0.52736,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.337681,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.159124, 1, 0, 0.520468,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.633242,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.458336,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0184215, 1, 0, 0.52559,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -0.976195, 0, -1, 0.32057,-99) , 
21, 0.523588, 0, 0, -0.104732, 0, 0.298999, -0.00334718, -0.104652, -0.31751, 0.185753, 0, 0, 0, -0.861745, 0.0464986, 11.5192, 0, 0, 0, -1.68402, 0.562999, 20, -0.0169564, 0, 0, 0.432681,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.914753, 0, 0, 0.505758,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.135605);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.72753,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.585168,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.434351,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 1.58534, 0, 0, 0.523683,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0.420749, 1, 0, 0.560085,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.536023,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.428576,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 2929.26, 0, 0, 0.511171,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, 0.074487, 0, -0.166276, -0.0696724, -0.113658, -0.11045, -0.171055, 0, 0, 0, 0.37585, 0.140626, 14.367, 0, 0, 0, -0.835295, 0.506857, -1, -0.00331299, 0, -1, 0.395368,-99) , 
21, 0, 0, 0, -0.0284349, 0, -0.0209423, 0.0110603, 0.0044531, -0.0441504, -0.126452, 0, 0, 0, 0.0666957, 0.0576697, 5.3416, 0, 0, 0, -0.56095, 0.209685, 20, -0.0311407, 0, 0, 0.481719,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.0226193, 1, 0, 0.495483,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.103963);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.523856,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.422033,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.932478, 0, 0, 0.507544,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.579799,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.328539,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.0182928, 1, 0, 0.427971,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, -0.0439156, 1, 0, 0.497449,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.519478,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.282642,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.67368, 0, 0, 0.38022,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.489338,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0934392);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.519547,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.400067,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 1.0929, 0, 0, 0.503283,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, 0, 0, 0.106498, -0.0593756, -0.0164397, 0.0169379, 0.145652, 0, 0, 0, -0.337105, 0, 3.77266, 0, 0, 0, -0.12431, -0.228729, -1, -0.0745278, 0, -1, 0.442636,-99) , 
21, 0, 0, 0, 0.00466787, 0, 0.0453027, 0.0105546, 0.0603577, 0.0141359, -0.0264476, 0, 0, 0, -0.108367, -0.00678063, 3.97319, 0, 0, 0, -0.480571, -0.0393377, 20, -0.0118106, 0, 0, 0.483545,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.518601,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.245375,-99) , 
21, 0, 0, 0, -0.245941, 0, -0.410281, 0.186889, 0.306946, -0.913014, 1.15138, 0, 0, 0, 1.49697, 0.32863, 6.30068, 0, 0, 0, -0.892091, 0.657318, 20, -0.0210117, 0, 0, 0.373227,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.87605, 0, 0, 0.47582,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.139293);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
21, 0, 0, 0, 0.0551952, 0, -0.0587477, -0.0187995, -0.198073, 0.184003, -0.748319, 0, 0, 0, 0.222956, -0.117581, 0, 0, 0, 0, 0, 0.784154, -1, 0.0266312, 0, 1, 0.555131,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.556846,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.445975,-99) , 
21, 0, 0, 0, -0.0335296, 0, 0, 0.0216113, 0.0999078, 0.0359066, 0.0178441, 0, 0, 0, 0, 0.0956347, 0, 0, 0, 0, 0, -0.334767, 20, 0.0273754, 0, 0, 0.467658,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.112903, 0, 0, 0.490112,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.555133,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.420264,-99) , 
21, 0, 0.484246, 0, 0.0814559, 0, 0.221345, 0.0654423, 0.137415, -0.26791, 0.117172, 0, 0, 0, -0.525262, -0.0635561, 7.72861, 0, 0, 0, -0.825532, 0.549877, 20, -0.00844726, 0, 0, 0.496585,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.6248, 0, -1, 0.347603,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0245643, 1, 0, 0.42491,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.787656, 0, 0, 0.472213,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.103461);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.71461,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.453883,-99) , 
21, 0, 0, 0, 0, 0, 0.0502193, 0.13887, -0.0817638, -0.518483, 0.947269, 0, 0, 0, 0.0209203, 0, -5.63459, 0, 0, 0, 0.847003, -0.0502595, 20, -0.00783906, 0, 0, 0.58906,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.697849,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.469083,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.97465, 0, 0, 0.481197,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.29012, 1, 0, 0.48862,-99) , 
NN_DD(
0, 
0, 
21, 0, 0.301568, 0, -0.413058, 0, 0.133027, 0.0650301, 0.140064, -0.426601, 0.5282, 0, 0, 0, -0.344754, 0.202494, 8.78943, 0, 0, 0, -2.10254, 0.324585, -1, -0.0375264, 0, -1, 0.375392,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.480909,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0965723);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.579333,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.48146,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.13424, 1, 0, 0.537528,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.512376,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.364353,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.64329, 0, 0, 0.485866,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.592595, 0, 0, 0.510118,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.517003,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.314336,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.67368, 0, 0, 0.399946,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.502672,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.123048);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.573524,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.487587,-99) , 
21, 0, 0, 0, 0.129225, 0, 0.0780786, -0.164485, -0.293322, -0.167692, 0.342643, 0, 0, 0, -0.15467, -0.0899929, 3.64506, 0, 0, 0, -0.345401, 0.340351, 20, -0.0132955, 0, 0, 0.543075,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.602679,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.32196,-99) , 
21, 0, 0, 0, 0, 0, 0, 0.261648, 4.38343, -0.41195, 0.732627, 0, 0, 0, 0.0171925, 0, 10.07, 0, 0, 0, 0.0759157, -0.762883, 20, -0.0241515, 0, 0, 0.43283,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 2.16886, 1, 0, 0.526496,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.61435,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.57926, 0, -1, 0.449446,-99) , 
21, 0, 0, 0, -0.0060613, 0, 0.0265754, -0.00070185, -0.126388, 0.0796292, -0.303695, 0, 0, 0, -0.0541771, 0.0383867, -1.23175, 0, 0, -0.0592087, -0.593194, 0.320229, 20, 0.0664195, 0, 0, 0.46559,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.592595, 0, 0, 0.493697,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.1124);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.605211,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.466103,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -2.15111, 0, 0, 0.564106,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.547489,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.474725,-99) , 
21, 0, 0, 0, -0.0779435, 0, -0.0402781, 0.00201317, 0.0402612, 0.0722973, -0.0952899, 0, 0, 0, 0.0181998, 0.128307, 4.38766, 0, 0, 0, -0.741794, -0.240556, 20, 0.011644, 0, 0, 0.504172,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 1.19551, 1, 0, 0.519794,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.655618,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0.0245643, 1, -1, 0.43218,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 10117.1, 0, 0, 0.461472,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.787656, 0, 0, 0.503971,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.101667);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.688942,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.523926,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.390537,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, -1.24473, 0, 0, 0.514867,-99) , 
21, 0, 0, 0, 0.00399775, 0, 0.0326984, -0.01271, -0.0417934, 0.0119624, -0.0680407, 0, 0, 0, -0.00400507, -0.0699387, 10.0142, 0, 0, 0, -0.898283, 0.230565, 20, 0.0533452, 0, 0, 0.524085,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.634903,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.420415,-99) , 
21, 0, -0.165553, 0, 0, 0, -0.404743, 0.0845548, 0.122794, 0.0761455, -0.371135, 0, 0, 0, 0.736354, 0, 9.3821, 0, 0, 0, -1.50666, 0.171735, 20, 0.0372676, 0, 0, 0.476971,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.35301,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 5540.69, 1, 0, 0.449827,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.08574, 0, 0, 0.510357,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.105198);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.53369,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.468506,-99) , 
21, 0, 0, 0, 0.100833, 0, 0.0108439, -0.104314, -0.230969, 0.051644, -0.112718, 0, 0, 0, -0.0403239, -0.0621006, 0.00252488, 0, 0, 0, -0.245802, 0.275977, 20, -0.00917224, 0, 0, 0.511938,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.616132,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.368245,-99) , 
21, 0, 0, 0, 0, 0, -0.194532, 0.195972, 3.25289, -0.0637498, 0.067488, 0, 0, 0, 0.0724938, 0, 7.28784, 0, 0, 0, -0.616233, -0.594016, 20, 0.040374, 0, 0, 0.441693,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 2.17109, 1, 0, 0.501591,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.535024,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.279641,-99) , 
21, 0, 0, 0, -0.19476, 0, -0.36014, 0.177636, 0.310935, -0.910337, 1.20726, 0, 0, 0, 1.26268, 0.2379, 7.12612, 0, 0, 0, -1.03148, 0.615948, 20, -0.0194205, 0, 0, 0.404056,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.87605, 0, 0, 0.495055,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0602436);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.618519,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.65493,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.491651,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1.0132, 0, 0, 0.497367,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.539384,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.396863,-99) , 
21, 0, 0, 0, 0, 0, 0, -0.0212993, 0.101527, -0.26632, 0.54248, 0, 0, 0, 0.0646559, 0, 7.474, 0, 0, 0, -0.276417, -0.0318051, 20, 0.0481727, 0, 0, 0.424575,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.68555, 1, 0, 0.4848,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.21028, 1, 0, 0.489562,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.121474);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.0535235, 0, 0, -0.113661, -0.215458, -0.0924337, -0.0207526, 0, 0, 0, 0.248101, 0.0971777, 1.42944, 0, 0, 0, -0.0742827, 0.49962, -1, -0.00428722, 0, 1, 0.585136,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1.29338, 1, -1, 0.398824,-99) , 
21, 0, 0, 0, 0.166081, 0, -0.0794677, -0.0360877, -0.034268, -0.0166535, 0.228112, 0, 0, 0, -0.151456, -0.093602, 1.76374, 0, 0, 0, -0.0957486, -0.277999, 20, -0.0481502, 0, 0, 0.541163,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.572276,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.411098,-99) , 
21, 0, 0, 0, 0, 0, 0.0942052, 0.0125418, -0.074782, 0.322562, -0.382708, 0, 0, 0, -0.446607, 0, -0.649712, 0, 0, 0, -0.53954, -0.404333, 20, -0.0606996, 0, 0, 0.543338,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, -0.148486, 0, -0.0683132, -0.0937704, -0.158629, -0.211197, 0.150077, 0, 0, 0, 0.385913, 0.183344, 0.7631, 0, 0, 0, 0.158314, 0.456227, -1, -0.0586569, 0, -1, 0.461586,-99) , 
21, 0, 0, 0, -0.149066, 0, -0.014113, 0.0217115, 0.00979594, -0.0265342, -0.0967983, 0, 0, 0, 0.152327, 0.0577594, 2.83875, 0, 0, 0, -0.303817, 0.229252, 20, 0.0146507, 0, 0, 0.48726,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0123819, 1, 0, 0.501733,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.125831);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.590549,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.485054,-99) , 
21, 0, 0, 0, 0.0402326, 0, 0, -0.0249025, -0.131438, -0.237993, 0.418414, 0, 0, 0, 0, -0.0389029, 15.7538, 0, 0, 0, -1.00464, 0.175451, 20, -0.028501, 0, 0, 0.561818,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.381537,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -1.66914, 1, 0, 0.543149,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.536001,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.3911,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, -0.289326, 1, 0, 0.517958,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -0.697909, 0, -1, 0.408165,-99) , 
21, 0, 0, 0, -0.0754305, 0, -0.0404279, 0.0119393, 0.0365936, -0.0995779, 0.0441759, 0, 0, 0, 0.0579309, 0.0592103, -0.932308, 0, 0, 0, -0.00657986, 0.119678, 20, -0.0197483, 0, 0, 0.491127,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.421867, 0, 0, 0.508247,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.144847);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.606403,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.42953,-99) , 
21, 0, 0, 0, -0.0701479, 0, 0.0506196, -0.0563083, -0.00863817, -0.0807566, 0.455531, 0, 0, 0, -0.272558, 0.413101, 2.64597, 0, 0, 0, 0.367822, -1.16986, 20, -0.0519112, 0, 0, 0.568297,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.537747,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.396964,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -1.94017, 1, 0, 0.499048,-99) , 
21, 0, 0, 0, 0.066817, 0, 0, 0.00598922, 0.0698344, -0.0427497, 0.0842096, 0, 0, 0, 0, 0.00698904, 6.1089, 0, 0, 0, -0.261767, -0.102831, 20, 0.00313397, 0, 0, 0.528958,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.581841,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.45239,-99) , 
21, 0, 0, 0, -0.0488232, 0, -0.0272539, -0.0338536, -0.0364284, 0.0786979, -0.030901, 0, 0, 0, -0.00583473, -0.137267, 15.7632, 0, 0, 0, -0.794563, 0.125527, 20, -0.0138108, 0, 0, 0.523403,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.504009,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.319717,-99) , 
21, 0, 0, 0, -0.137738, 0, -0.00138787, 0.0289136, 0.0267288, -0.018097, -0.396154, 0, 0, 0, 0.347107, 0.230926, 11.7135, 0, 0, 0, -1.68576, 0.434757, 20, -0.0202337, 0, 0, 0.431863,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.55521, 0, 0, 0.473245,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.543797, 0, 0, 0.498275,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0763893);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.630328,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.506076,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.432348,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.856342, 0, 0, 0.492647,-99) , 
21, 0, 0, 0, -0.00342486, 0, 0, -0.00231824, 0.00420537, -0.0502301, 0.168478, 0, 0, 0, -0.0519873, 0.0085816, -1.6595, 0, 0, 0, 0.389672, -0.148666, 20, 0.0355822, 0, 0, 0.499453,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.532725,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.320652,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.0997, 0, 0, 0.481912,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.238174,-99) , 
21, 0, 0, 0, -0.0132813, 0, 0, -0.010228, -0.236725, 0.852319, -2.10254, 0, 0, 0, 0.142538, 0.0529337, 0.125394, 0, 0, 0, -1.12755, 0.734961, 20, -0.0753079, 0, 0, 0.422692,-99) , 
21, 0, 0, 0, 0.00290676, 0, -0.00503418, 0.0103737, 0.0343437, -0.0541237, 0.0711705, 0, 0, 0, 0.0657801, -0.017591, 0.218753, 0, 0, 0, -0.00397061, 0.0739942, 20, -0.0128999, 0, 0, 0.48675,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.100586);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.527927,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.468776,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.29291, 0, 0, 0.501825,-99) , 
NN_DD(
0, 
0, 
21, 0, 0.0754972, 0, 0, 0, -0.13265, 0.150377, 0.326166, -0.133588, 0.332037, 0, 0, 0, 0.0658699, 0, 1.80267, 0, 0, 0, -0.721723, -0.384559, -1, -0.0450308, 0, -1, 0.421282,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 3.06334, 0, 0, 0.488408,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.572868,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.433329,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -0.435768, 0, 0, 0.478296,-99) , 
NN_DD(
0, 
0, 
21, 0, 0, 0, 0, 0, 0, -0.0296755, 0.325436, -0.201397, 0.557244, 0, 0, 0, -0.124688, 0, 7.23828, 0, 0, 0, -0.204844, -0.374353, -1, 0.012908, 0, -1, 0.352283,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.52607, 1, 0, 0.420679,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.68555, 1, 0, 0.475788,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0454303);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 2.69037, 1, -1, 0.493384,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.54649,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.278814,-99) , 
21, 0, 0, 0, -0.070347, 0, -0.210497, -0.101357, -0.37477, -0.949554, 1.03799, 0, 0, 0, 0.999349, -0.126866, 8.33321, 0, 0, 0, 0.492259, 1.73924, 20, 0.0275896, 0, 0, 0.398552,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0866495, 1, 0, 0.486464,-99) , 
NN_DD(
0, 
0, 
21, 0, 0.147507, 0, -0.400774, 0, 0.122746, 0.0863395, 0.259426, -0.277567, 0.436606, 0, 0, 0, -0.257727, 0.252829, 8.52903, 0, 0, 0, -1.81965, -0.143873, -1, 0.00500589, 0, -1, 0.389997,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.480136,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0534598);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.509159,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.378055,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 2.69037, 1, 0, 0.504741,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 3.67368, 0, -1, 0.403547,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.03151, 0, 0, 0.497692,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.534282,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.279346,-99) , 
21, 0, 0, 0, -0.0500436, 0, -0.204849, -0.0980877, -0.361674, -0.87253, 0.9384, 0, 0, 0, 0.950807, -0.139755, 8.0725, 0, 0, 0, 0.4369, 1.6646, 20, 0.0212841, 0, 0, 0.396546,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0866495, 1, 0, 0.49079,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0715598);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.603086,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.513294,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.464798,-99) , 
21, 0, 0, 0, 0.00316505, 0, -0.0110538, 0.017291, 0.0455893, 0.032027, -0.09085, 0, 0, 0, 0.0119835, -0.0501105, -0.590769, 0, 0, 0, -0.125696, 0.0939641, 20, 0.00489485, 0, 0, 0.482837,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1.00516, 0, 0, 0.487017,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.516457,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.292424,-99) , 
21, 0, 0, 0, -0.0435888, 0, -0.188352, -0.0917668, -0.346117, -0.790167, 0.840432, 0, 0, 0, 0.872453, -0.137829, 7.51807, 0, 0, 0, 0.382386, 1.54864, 20, 0.0164948, 0, 0, 0.396879,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0866495, 1, 0, 0.480901,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0488547);
  fForest.push_back( 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.642629,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1.68555, 1, -1, 0.479396,-99) , 
21, 0, 0, 0, 0.000190436, 0, 0.000622361, 0.0003037, 0.0157737, -0.0267473, 0.0437454, 0, 0, 0, 0.0158256, 0.0231722, 1.0223, 0, 0, 0, -0.0485888, -0.0287456, 20, 0.0151682, 0, 0, 0.484484,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0577825);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.710505,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.613884,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.467661,-99) , 
21, 0, 0, 0, 0, 0, 0.0517759, -0.0132695, 0.145076, 0.0719916, 0.0659181, 0, 0, 0, -0.0178283, 0, -9.31656, 0, 0, 0, 1.65601, -0.385087, 20, 0.0167989, 0, 0, 0.530912,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.96826, 0, 0, 0.568062,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -2.87605, 0, -1, 0.483198,-99) , 
21, 0, 0, 0, 0.00104663, 0, 0.000798208, 6.6837e-06, 0.011787, -0.0158776, 0.0255719, 0, 0, 0, 0.010754, 0.0196382, 0.742296, 0, 0, 0, -0.038889, -0.0267061, 20, 0.00683505, 0, 0, 0.495929,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0840361);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.531647,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.37798,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1.12952, 0, 0, 0.52507,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.518746,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.396149,-99) , 
21, 0, 0, 0, 0, 0, 0, -0.0113937, 0.131396, -0.268767, 0.580953, 0, 0, 0, 0.00930702, 0, 7.13005, 0, 0, 0, -0.129104, -0.140164, 20, -0.0129887, 0, 0, 0.466438,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, -1.68555, 1, 0, 0.514233,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.501642,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.298058,-99) , 
21, 0, 0, 0, -0.036439, 0, -0.170351, -0.0843259, -0.345569, -0.653673, 0.65229, 0, 0, 0, 0.770278, -0.143603, 6.43796, 0, 0, 0, 0.305623, 1.42308, 20, -0.0329652, 0, 0, 0.421143,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0866495, 1, 0, 0.508001,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0582806);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.530345,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.48587,-99) , 
21, 0, 0, 0, -0.014011, 0, -0.0112371, 0.000795924, -0.00136437, 0.0667043, -0.119694, 0, 0, 0, -0.02206, 0.00545589, -0.535737, 0, 0, 0, -0.0904857, -0.0191834, 20, 0.00411758, 0, 0, 0.50202,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.384548,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.159105, 1, 0, 0.498524,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.525887,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.292192,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.655157, 0, 0, 0.407374,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, -2.87605, 0, 0, 0.492547,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0796951);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.637059,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.715377,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.487036,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.9834, 0, 0, 0.498672,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 1.31081, 1, 0, 0.505503,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.553736,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.367476,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.757376, 0, 0, 0.492424,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.297587,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0370443, 1, 0, 0.433061,-99) , 
21, 0, 0, 0, 0.0196025, 0, 0.0072029, 0.0013709, -0.00478455, -0.0448552, 0.0750227, 0, 0, 0, 0.0145316, -0.00528648, 0.507925, 0, 0, 0, 0.0178427, 0.0184037, 20, -0.010004, 0, 0, 0.496574,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.113498);
  fForest.push_back( 
NN_DD(
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.557227,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.49362,-99) , 
21, 0, 0, 0, 0.0951143, 0, -0.0385366, -0.00839021, -0.0328782, 0.0218036, -0.0463007, 0, 0, 0, 0.0272407, -0.0310544, -4.4338, 0, 0, 0, 0.312917, 0.0144993, 20, -0.005256, 0, 0, 0.533897,-99) , 
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.587527,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.380788,-99) , 
21, 0, 0, 0, -0.245816, 0, -0.0562354, 0.125652, 3.05405, -0.0955582, 0.165333, 0, 0, 0, 0.000133324, -0.130729, 10.225, 0, 0, 0, -0.731878, -0.0274067, 20, 0.0135386, 0, 0, 0.466432,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 2.17109, 1, 0, 0.52304,-99) , 
NN_DD(
NN_DD(
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 1, 0.648234,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.461272,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 0.0203095, 1, 0, 0.494127,-99) , 
NN_DD(
0, 
0, 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, -1, 0.246459,-99) , 
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 0.0555479, 1, 0, 0.455442,-99) , 
21, 0, 0, 0, 0.0248605, 0, 0.00959618, 0.000724897, -0.00990576, -0.056901, 0.0920777, 0, 0, 0, 0.0188249, -0.000281488, 0.590116, 0, 0, 0, 0.0200838, 0.0206902, 20, -0.0105403, 0, 0, 0.510817,-99)    );
   return;
};
 
// Clean up
inline void ReadBDTDD2012Fisher::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTDD2012Fisher::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
